### ISSUE TITLE
Include wait_for_update on the setDefaultConsent Call

### ISSUE THREAD

**Issue by semisight** [Cookie-Script/GTM-tag-template#1] opened 2022-05-12 21:37 UTC
When reviewing your template we've noticed that the setDefaultConsentState call does not include the [wait_for_update](https://developers.google.com/tag-platform/tag-manager/templates/api#setdefaultconsentstate) option. This is required for any asynchronous consent management script load to delay tag execution.

**Comment by Cookie-Script** [comment] 2022-05-23 08:15
@semisight The issue is now fixed, please review

**Closed as completed by Cookie-Script** 2022-05-23 08:15 UTC

**Comment by Cookie-Script** [comment] 2022-06-06 14:00
@semisight Can you please review and validate the template at Community Template Gallery?

**Comment by Cookie-Script** [comment] 2023-02-22 15:29
@semisight the issue has been resolved, please re-validate the template. It's been 9 months since the issue was resolved and the template is still not added to the template gallery.

**Comment by semisight** [comment] 2023-03-23 20:36
Apologies, this pull request just slipped through the cracks. Your template should be available in Gallery momentarily.
